[build]
  command = "pip install -r requirements.txt && python seed_data.py"
  functions = "netlify/functions"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.10"

[functions]
  included_files = ["templates/**", "pulsecare.db", "schema.sql", "models.py", "app.py", "static/**"]

[[redirects]]
  from = "/static/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
