services:
  - type: web
    name: pulsecare-hms
    env: python
    buildCommand: pip install -r requirements.txt && python seed_data.py
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
